interface GameData {
  interestedInFeatures?: string[];
  description: string;
}

export enum GameKey {
  LeagueOfLegends = 5426,
  CS2 = 22730,
  RocketLeague = 10798,
  PUBG = 10906,
  Fortnite = 21216,
  ApexLegends = 21566,
  Valorant = 21640,
  CSGO = 7764
}

export const GameFileName = {
  [GameKey.LeagueOfLegends]: 'League Of Legends',
  [GameKey.CS2]: 'Counter Strike 2',
  [GameKey.RocketLeague]: 'Rocket League',
  [GameKey.PUBG]: 'PUBG',
  [GameKey.Fortnite]: 'Fortnite',
  [GameKey.ApexLegends]: 'Apex Legends',
  [GameKey.Valorant]: 'Valorant',
  [GameKey.CSGO]: 'Counter Strike GO',
}

const data: { [id: number]: GameData } = {
  [GameKey.LeagueOfLegends]: {
    interestedInFeatures: [
      'summoner_info',
      'gameMode',
      'teams',
      'matchState',
      'kill',
      'death',
      'respawn',
      'assist',
      'minions',
      'level',
      'abilities',
      'announcer',
      'counters',
      'match_info',
      'damage',
      'heal',
      'live_client_data',
      'jungle_camps',
      'team_frames',
    ],
    description: 'LOL data',
  },
  [GameKey.CS2]: {
    interestedInFeatures: [
      'gep_internal',
      'match_info',
      'live_data',
    ],
    description: 'CS:GO data',
  },
  [GameKey.RocketLeague]: {
    interestedInFeatures: [
      'stats',
      'roster',
      'match',
      'me',
      'match_info',
      'death',
      'game_info',
    ],
    description: 'Rocket league data',
  },
  [GameKey.PUBG]: {
    interestedInFeatures: [
      'kill',
      'revived',
      'death',
      'killer',
      'match',
      'rank',
      'location',
      'me',
      'team',
      'phase',
      'map',
      'roster',
      'inventory',
      'match_info',
      'counters',
    ],
    description: 'PUBG data',
  },
  [GameKey.Fortnite]: {
    interestedInFeatures: [
      'kill',
      'killed',
      'killer',
      'revived',
      'death',
      'match',
      'rank',
      'me',
      'phase',
      'location',
      'roster',
      'team',
      'items',
      'counters',
      'match_info',
      'map',
    ],
    description: 'Fortnite data',
  },
  [GameKey.ApexLegends]: {
    interestedInFeatures: [
      'death',
      'kill',
      'match_state',
      'me',
      'revive',
      'team',
      'roster',
      'kill_feed',
      'rank',
      'match_summary',
      'location',
      'match_info',
      'victory',
      'damage',
      'inventory',
      'localization',
    ],
    description: 'Apex data',
  },
  [GameKey.Valorant]: {
    interestedInFeatures: [
      'game_info',
      'me',
      'match_info',
      'kill',
      'death',
      'gep_internal',
    ],
    description: 'Valorant data',
  },
  [GameKey.CSGO]: {
    interestedInFeatures: [
      'kill',
      'death',
      'assist',
      'headshot',
      'round_start',
      'match_start',
      'match_end',
      'team_round_win',
      'bomb_planted',
      'bomb_change',
      'reloading',
      'fired',
      'weapon_change',
      'weapon_acquired',
      'player_activity_change',
      'team_set',
      'info',
      'roster',
      'scene',
      'match_info',
      'replay',
      'counters',
      'mvp',
      'kill_feed',
      'scoreboard',
      'score',
    ],
    description: 'CS:GO data',
  },
};

export default data;
